disable celeborn; disable random kill test
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>

diff --git a/.github/workflows/velox_docker.yml b/.github/workflows/velox_docker.yml
--- a/.github/workflows/velox_docker.yml
+++ b/.github/workflows/velox_docker.yml
@@ -179,75 +179,157 @@ jobs:
           && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
             --local --preset=velox --benchmark-type=h --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 \
           && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
-            --local --preset=velox --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1            
+            --local --preset=velox --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1
+     
+  # run-tpc-test-centos8-oom-randomkill:
+  #   needs: build-native-lib
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       spark: ["spark-3.2"]
+  #   runs-on: ubuntu-20.04
+  #   container: centos:8
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Download All Artifacts
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: velox-native-lib-${{github.sha}}
+  #         path: ./cpp/build/releases
+  #     - name: Update mirror list
+  #       run: |
+  #         sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* || true
+  #         sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-* || true
+  #     - name: Setup java and maven
+  #       run: |
+  #         yum update -y && yum install -y java-1.8.0-openjdk-devel wget
+  #         wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
+  #         tar -xvf apache-maven-3.8.8-bin.tar.gz
+  #         mv apache-maven-3.8.8 /usr/lib/maven
+  #     - name: Build for Spark ${{ matrix.spark }}
+  #       run: |
+  #         cd $GITHUB_WORKSPACE/ 
+  #         export MAVEN_HOME=/usr/lib/maven
+  #         export PATH=${PATH}:${MAVEN_HOME}/bin
+  #         mvn clean install -P${{ matrix.spark }} -Pbackends-velox -DskipTests
+  #     - name: TPC-DS SF30.0 Parquet local spark3.2 Q67/Q95 low memory, memory isolation off
+  #       run: |
+  #         export MAVEN_HOME=/usr/lib/maven
+  #         export PATH=${PATH}:${MAVEN_HOME}/bin
+  #         cd tools/gluten-it && \
+  #         mvn clean install -Pspark-3.2 \
+  #         && GLUTEN_IT_JVM_ARGS=-Xmx50G sbin/gluten-it.sh parameterized \
+  #           --local --preset=velox --benchmark-type=ds --error-on-memleak --queries=q67,q95 -s=30.0 --threads=12 --shuffle-partitions=72 --iterations=1 \
+  #           --skip-data-gen -m=OffHeapExecutionMemory \
+  #           -d=ISOLATION:OFF,spark.gluten.memory.isolation=false \
+  #           -d=OFFHEAP_SIZE:5g,spark.memory.offHeap.size=5g \
+  #           -d=OFFHEAP_SIZE:3g,spark.memory.offHeap.size=3g \
+  #           -d=OVER_ACQUIRE:0.3,spark.gluten.memory.overAcquiredMemoryRatio=0.3 \
+  #           -d=OVER_ACQUIRE:0.5,spark.gluten.memory.overAcquiredMemoryRatio=0.5
+  #     - name: (To be fixed) TPC-DS SF30.0 Parquet local spark3.2 Q67/Q95 low memory, memory isolation on
+  #       run: |
+  #         export MAVEN_HOME=/usr/lib/maven
+  #         export PATH=${PATH}:${MAVEN_HOME}/bin
+  #         cd tools/gluten-it && \
+  #         mvn clean install -Pspark-3.2 \
+  #         && GLUTEN_IT_JVM_ARGS=-Xmx50G sbin/gluten-it.sh parameterized \
+  #           --local --preset=velox --benchmark-type=ds --error-on-memleak --queries=q67,q95 -s=30.0 --threads=12 --shuffle-partitions=72 --iterations=1 \
+  #           --skip-data-gen -m=OffHeapExecutionMemory \
+  #           -d=ISOLATION:ON,spark.gluten.memory.isolation=true,spark.memory.storageFraction=0.1 \
+  #           -d=OFFHEAP_SIZE:5g,spark.memory.offHeap.size=5g \
+  #           -d=OFFHEAP_SIZE:3g,spark.memory.offHeap.size=3g \
+  #           -d=OVER_ACQUIRE:0.3,spark.gluten.memory.overAcquiredMemoryRatio=0.3 \
+  #           -d=OVER_ACQUIRE:0.5,spark.gluten.memory.overAcquiredMemoryRatio=0.5 || true
+  #     - name: TPC-DS SF30.0 Parquet local spark3.2 Q23A/Q23B low memory
+  #       run: |
+  #         cd tools/gluten-it && \
+  #         GLUTEN_IT_JVM_ARGS=-Xmx50G sbin/gluten-it.sh parameterized \
+  #           --local --preset=velox --benchmark-type=ds --error-on-memleak --queries=q23a,q23b -s=30.0 --threads=12 --shuffle-partitions=72 --iterations=1 \
+  #           --skip-data-gen -m=OffHeapExecutionMemory \
+  #           -d=ISOLATION:OFF,spark.gluten.memory.isolation=false \
+  #           -d=ISOLATION:ON,spark.gluten.memory.isolation=true,spark.memory.storageFraction=0.1 \
+  #           -d=OFFHEAP_SIZE:2g,spark.memory.offHeap.size=2g \
+  #           -d=FLUSH_MODE:DISABLED,spark.gluten.sql.columnar.backend.velox.flushablePartialAggregation=false,spark.gluten.sql.columnar.backend.velox.maxPartialAggregationMemoryRatio=1.0,spark.gluten.sql.columnar.backend.velox.maxExtendedPartialAggregationMemoryRatio=1.0,spark.gluten.sql.columnar.backend.velox.abandonPartialAggregationMinPct=100,spark.gluten.sql.columnar.backend.velox.abandonPartialAggregationMinRows=0 \
+  #           -d=FLUSH_MODE:ABANDONED,spark.gluten.sql.columnar.backend.velox.maxPartialAggregationMemoryRatio=1.0,spark.gluten.sql.columnar.backend.velox.maxExtendedPartialAggregationMemoryRatio=1.0,spark.gluten.sql.columnar.backend.velox.abandonPartialAggregationMinPct=0,spark.gluten.sql.columnar.backend.velox.abandonPartialAggregationMinRows=0 \
+  #           -d=FLUSH_MODE:FLUSHED,spark.gluten.sql.columnar.backend.velox.maxPartialAggregationMemoryRatio=0.05,spark.gluten.sql.columnar.backend.velox.maxExtendedPartialAggregationMemoryRatio=0.1,spark.gluten.sql.columnar.backend.velox.abandonPartialAggregationMinPct=100,spark.gluten.sql.columnar.backend.velox.abandonPartialAggregationMinRows=0
+  #     - name: (To be fixed) TPC-DS SF30.0 Parquet local spark3.2 Q97 low memory # The case currently causes crash with "free: invalid size".
+  #       run: |
+  #         cd tools/gluten-it && \
+  #         GLUTEN_IT_JVM_ARGS=-Xmx50G sbin/gluten-it.sh parameterized \
+  #           --local --preset=velox --benchmark-type=ds --error-on-memleak --queries=q97 -s=30.0 --threads=12 --shuffle-partitions=72 --iterations=1 \
+  #           --skip-data-gen -m=OffHeapExecutionMemory \
+  #           -d=ISOLATION:OFF,spark.gluten.memory.isolation=false \
+  #           -d=ISOLATION:ON,spark.gluten.memory.isolation=true,spark.memory.storageFraction=0.1 \
+  #           -d=OFFHEAP_SIZE:2g,spark.memory.offHeap.size=2g \
+  #           -d=OFFHEAP_SIZE:1g,spark.memory.offHeap.size=1g || true
 
-  run-tpc-test-centos8-celeborn:
-    needs: build-native-lib
-    strategy:
-      fail-fast: false
-      matrix:
-        spark: ["spark-3.2"]
-    runs-on: ubuntu-20.04
-    container: centos:8
-    steps:
-      - uses: actions/checkout@v2
-      - name: Download All Artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: velox-native-lib-${{github.sha}}
-          path: ./cpp/build/releases
-      - name: Update mirror list
-        run: |
-          sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* || true
-          sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-* || true
-      - name: Setup java and maven
-        run: |
-          yum update -y && yum install -y java-1.8.0-openjdk-devel wget
-          wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
-          tar -xvf apache-maven-3.8.8-bin.tar.gz
-          mv apache-maven-3.8.8 /usr/lib/maven
-      - name: Build for Spark ${{ matrix.spark }}
-        run: |
-          cd $GITHUB_WORKSPACE/ 
-          export MAVEN_HOME=/usr/lib/maven
-          export PATH=${PATH}:${MAVEN_HOME}/bin
-          mvn clean install -P${{ matrix.spark }} -Pbackends-velox -DskipTests
-      - name: TPC-H SF1.0 && TPC-DS SF1.0 Parquet local spark3.2 with Celeborn 0.4.0
-        run: |
-          export MAVEN_HOME=/usr/lib/maven
-          export PATH=${PATH}:${MAVEN_HOME}/bin
-          cd /opt && mkdir -p celeborn && \
-          wget https://archive.apache.org/dist/incubator/celeborn/celeborn-0.4.0-incubating/apache-celeborn-0.4.0-incubating-bin.tgz && \
-          tar xzf apache-celeborn-0.4.0-incubating-bin.tgz -C /opt/celeborn --strip-components=1 && cd celeborn && \
-          mv ./conf/celeborn-env.sh.template ./conf/celeborn-env.sh && \
-          echo -e "CELEBORN_MASTER_MEMORY=4g\nCELEBORN_WORKER_MEMORY=4g\nCELEBORN_WORKER_OFFHEAP_MEMORY=8g" > ./conf/celeborn-env.sh && \
-          echo -e "celeborn.worker.commitFiles.threads 128\nceleborn.worker.sortPartition.threads 64" > ./conf/celeborn-defaults.conf \
-          && bash ./sbin/start-master.sh && bash ./sbin/start-worker.sh && \
-          cd $GITHUB_WORKSPACE/tools/gluten-it && mvn clean install -Pspark-3.2,rss,celeborn-0.4 \
-          && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
-            --local --preset=velox-with-celeborn --benchmark-type=h --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 \
-          && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
-            --local --preset=velox-with-celeborn --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 && \
-          bash /opt/celeborn/sbin/stop-worker.sh \
-          && bash /opt/celeborn/sbin/stop-master.sh && rm -rf /opt/celeborn
-      - name: TPC-H SF1.0 && TPC-DS SF10.0 Parquet local spark3.2 with Celeborn 0.3.2
-        run: |
-          export MAVEN_HOME=/usr/lib/maven
-          export PATH=${PATH}:${MAVEN_HOME}/bin
-          cd /opt && mkdir -p celeborn && \
-          wget https://archive.apache.org/dist/incubator/celeborn/celeborn-0.3.2-incubating/apache-celeborn-0.3.2-incubating-bin.tgz && \
-          tar xzf apache-celeborn-0.3.2-incubating-bin.tgz -C /opt/celeborn --strip-components=1 && cd celeborn && \
-          mv ./conf/celeborn-env.sh.template ./conf/celeborn-env.sh && \
-          echo -e "CELEBORN_MASTER_MEMORY=4g\nCELEBORN_WORKER_MEMORY=4g\nCELEBORN_WORKER_OFFHEAP_MEMORY=8g" > ./conf/celeborn-env.sh && \
-          echo -e "celeborn.worker.commitFiles.threads 128\nceleborn.worker.sortPartition.threads 64" > ./conf/celeborn-defaults.conf \
-          && bash ./sbin/start-master.sh && bash ./sbin/start-worker.sh && \
-          cd $GITHUB_WORKSPACE/tools/gluten-it && mvn clean install -Pspark-3.2,rss \
-          && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
-            --local --preset=velox-with-celeborn --benchmark-type=h --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 \
-          && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
-            --local --preset=velox-with-celeborn --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 && \
-          bash /opt/celeborn/sbin/stop-worker.sh \
-          && bash /opt/celeborn/sbin/stop-master.sh
+  # run-tpc-test-centos8-celeborn:
+  #   needs: build-native-lib
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       spark: ["spark-3.2"]
+  #   runs-on: ubuntu-20.04
+  #   container: centos:8
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Download All Artifacts
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: velox-native-lib-${{github.sha}}
+  #         path: ./cpp/build/releases
+  #     - name: Update mirror list
+  #       run: |
+  #         sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* || true
+  #         sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-* || true
+  #     - name: Setup java and maven
+  #       run: |
+  #         yum update -y && yum install -y java-1.8.0-openjdk-devel wget
+  #         wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
+  #         tar -xvf apache-maven-3.8.8-bin.tar.gz
+  #         mv apache-maven-3.8.8 /usr/lib/maven
+  #     - name: Build for Spark ${{ matrix.spark }}
+  #       run: |
+  #         cd $GITHUB_WORKSPACE/ 
+  #         export MAVEN_HOME=/usr/lib/maven
+  #         export PATH=${PATH}:${MAVEN_HOME}/bin
+  #         mvn clean install -P${{ matrix.spark }} -Pbackends-velox -DskipTests
+  #     - name: TPC-H SF1.0 && TPC-DS SF1.0 Parquet local spark3.2 with Celeborn 0.4.0
+  #       run: |
+  #         export MAVEN_HOME=/usr/lib/maven
+  #         export PATH=${PATH}:${MAVEN_HOME}/bin
+  #         cd /opt && mkdir -p celeborn && \
+  #         wget https://archive.apache.org/dist/incubator/celeborn/celeborn-0.4.0-incubating/apache-celeborn-0.4.0-incubating-bin.tgz && \
+  #         tar xzf apache-celeborn-0.4.0-incubating-bin.tgz -C /opt/celeborn --strip-components=1 && cd celeborn && \
+  #         mv ./conf/celeborn-env.sh.template ./conf/celeborn-env.sh && \
+  #         echo -e "CELEBORN_MASTER_MEMORY=4g\nCELEBORN_WORKER_MEMORY=4g\nCELEBORN_WORKER_OFFHEAP_MEMORY=8g" > ./conf/celeborn-env.sh && \
+  #         echo -e "celeborn.worker.commitFiles.threads 128\nceleborn.worker.sortPartition.threads 64" > ./conf/celeborn-defaults.conf \
+  #         && bash ./sbin/start-master.sh && bash ./sbin/start-worker.sh && \
+  #         cd $GITHUB_WORKSPACE/tools/gluten-it && mvn clean install -Pspark-3.2,rss,celeborn-0.4 \
+  #         && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
+  #           --local --preset=velox-with-celeborn --benchmark-type=h --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 \
+  #         && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
+  #           --local --preset=velox-with-celeborn --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 && \
+  #         bash /opt/celeborn/sbin/stop-worker.sh \
+  #         && bash /opt/celeborn/sbin/stop-master.sh && rm -rf /opt/celeborn
+  #     - name: TPC-H SF1.0 && TPC-DS SF10.0 Parquet local spark3.2 with Celeborn 0.3.2
+  #       run: |
+  #         export MAVEN_HOME=/usr/lib/maven
+  #         export PATH=${PATH}:${MAVEN_HOME}/bin
+  #         cd /opt && mkdir -p celeborn && \
+  #         wget https://archive.apache.org/dist/incubator/celeborn/celeborn-0.3.2-incubating/apache-celeborn-0.3.2-incubating-bin.tgz && \
+  #         tar xzf apache-celeborn-0.3.2-incubating-bin.tgz -C /opt/celeborn --strip-components=1 && cd celeborn && \
+  #         mv ./conf/celeborn-env.sh.template ./conf/celeborn-env.sh && \
+  #         echo -e "CELEBORN_MASTER_MEMORY=4g\nCELEBORN_WORKER_MEMORY=4g\nCELEBORN_WORKER_OFFHEAP_MEMORY=8g" > ./conf/celeborn-env.sh && \
+  #         echo -e "celeborn.worker.commitFiles.threads 128\nceleborn.worker.sortPartition.threads 64" > ./conf/celeborn-defaults.conf \
+  #         && bash ./sbin/start-master.sh && bash ./sbin/start-worker.sh && \
+  #         cd $GITHUB_WORKSPACE/tools/gluten-it && mvn clean install -Pspark-3.2,rss \
+  #         && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
+  #           --local --preset=velox-with-celeborn --benchmark-type=h --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 \
+  #         && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
+  #           --local --preset=velox-with-celeborn --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 && \
+  #         bash /opt/celeborn/sbin/stop-worker.sh \
+  #         && bash /opt/celeborn/sbin/stop-master.sh
 
   run-spark-test-spark32:
     runs-on: ubuntu-20.04
